### ISSUE TITLE
pointnet2 module install error

### ISSUE THREAD

**Issue by stevenlin510** [UncleMEDM/PUGAN-pytorch#10]
![擷取](https://user-images.githubusercontent.com/48921883/105578791-a72edb00-5dbd-11eb-8cac-aa22d799e3d7.JPG)
When I type :　python setup.py install 
I got this error, and I try lots of time, the python dependency is same as requirement.txt you provided.
I'am so confused about this error, so please give me a favor !! Thanks

**Comment by UncleMEDM** [comment]
Can you provide more information? It is the pointnet2 codes from https://github.com/facebookresearch/votenet/tree/master/pointnet2. It is possible that your CUDA and pytorch version does not match. Also you can try uninstall ninja firstly then install the pointnet2.

**Comment by stevenlin510** [comment]
I uninstall ninja firstly then install the pointnet2 works thanks!
